# euroc:
  # - MH_01_easy
  # - MH_02_easy
  # - MH_03_medium
  # - MH_04_difficult
  # - MH_05_difficult
  # - V1_01_easy
  # - V1_02_medium
  ## - V1_03_difficult
  # - V2_01_easy
  # - V2_02_medium
  ##- V2_03_difficult

# rgbdtum:
  # - rgbd_dataset_freiburg1_xyz
  ##- rgbd_dataset_freiburg1_rpy
  ##- rgbd_dataset_freiburg1_360
  # - rgbd_dataset_freiburg1_floor
  ##- rgbd_dataset_freiburg1_desk
  ##- rgbd_dataset_freiburg1_desk2  
  ##- rgbd_dataset_freiburg1_room
  # - rgbd_dataset_freiburg1_plant
  ##- rgbd_dataset_freiburg1_teddy

euroc:
  - V1_03_difficult
  - V2_03_difficult
  - MH_01_easy
  - MH_02_easy
  - MH_03_medium
  - MH_04_difficult
  - MH_05_difficult
  - V1_01_easy
  - V1_02_medium
  # - V1_03_difficult
  - V2_01_easy
  - V2_02_medium
  #- V2_03_difficult

rgbdtum:
  - rgbd_dataset_freiburg1_xyz
  - rgbd_dataset_freiburg1_floor
  - rgbd_dataset_freiburg1_desk
  - rgbd_dataset_freiburg1_plant
  - rgbd_dataset_freiburg1_rpy
  - rgbd_dataset_freiburg1_teddy  
  - rgbd_dataset_freiburg1_room
  - rgbd_dataset_freiburg1_360
  - rgbd_dataset_freiburg1_desk2  
  # - rgbd_dataset_freiburg1_room
  # - rgbd_dataset_freiburg1_teddy  