# exp_vslamlabbench_mono_orbslam2:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 3
#   Parameters: {verbose: 0}
#   Module: orbslam2


# exp_vslamlabbench_mono_dpvo:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 3
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_vslamlabbench_mono_dpvo_dev:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 3
#   Parameters: {verbose: 0}
#   Module: dpvo-dev

################################################################
# ALLFeature-SLAM Benchmark ABLATION
# exp_vslamlabbench_mono_allfeature_ablation_kaze:
#   Config: config_ablation.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1} 
#   Module: allfeature-dev  

# exp_vslamlabbench_mono_allfeature_ablation_kaze_orb:
#   Config: config_ablation.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1} 
#   Module: allfeature-dev  

# exp_vslamlabbench_mono_allfeature_ablation_kaze_akaze:
#   Config: config_ablation.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1} 
#   Module: allfeature-dev  

# exp_vslamlabbench_mono_allfeature_ablation_kaze_brisk:
#   Config: config_ablation.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1} 
#   Module: allfeature-dev  

################################################################
# ALLFeature-SLAM Benchmark
# exp_vslamlabbench_mono_orbslam2_dev_27_01_25:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 4
#   Parameters: {verbose: 0}
#   Module: orbslam2-dev

# exp_vslamlabbench_mono_droidslam_dev_27_01_25:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: droidslam-dev

exp_vslamlabbench_mono_orbslam3_dev_31_01_25:
  Config: config_vslamlabbench.yaml
  NumRuns: 1
  Parameters: {verbose: 0, mode: 'mono'}
  Module: orbslam3-dev

# exp_vslamlabbench_mono_dpvo_dev_27_01_25:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: dpvo-dev

# exp_vslamlabbench_mono_allfeature_27_01_25:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 4
#   Parameters: {verbose: 0} 
#   Module: allfeature-dev  
  
# exp_vslamlabbench_mono_droidslam_26_01_25:
#   Config: config_vslamlabbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: droidslam

################################################################
# DROID-SLAM Benchmark

# exp_vslamlabbench_mono_allfeature:
#   Config: config_droidbench.yaml
#   NumRuns: 5
#   Parameters: {verbose: 0} 
#   Module: allfeature-dev  

# exp_vslamlabbench_mono_orbslam2_dev:
#   Config: config_droidbench.yaml
#   NumRuns: 5
#   Parameters: {verbose: 0}
#   Module: orbslam2-dev

# exp_vslamlabbench_mono_droidslam_dev:
#   Config: config_droidbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: droidslam-dev

# exp_vslamlabbench_mono_droidslam:
#   Config: config_droidbench.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: droidslam

# exp_vslamlabbench_mono_dpvo:
#   Config: config_droidbench.yaml
#   NumRuns: 4
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_vslamlabbench_mono_dpvo_dev:
#   Config: config_droidbench.yaml
#   NumRuns: 4
#   Parameters: {verbose: 0}
#   Module: dpvo-dev

# exp_vslamlabbench_mono_orbslam3_dev:
#   Config: config_droidbench.yaml
#   NumRuns: 4
#   Parameters: {verbose: 0}
#   Module: orbslam3-dev