exp_vitum_orbslam3:
  Config: config_vitum.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: stereo-vi, rgb_idx: [0,2000]}
  Module: orbslam3

exp_vitum_okvis2:
  Config: config_vitum.yaml
  NumRuns: 1
  Parameters: {verbose: 1, mode: mono-vi, rgb_idx: [0,2000]}
  Module: okvis2