test_exp_rgbd_droidslam:
  Config: test_config_rgbd.yaml
  NumRuns: 2
  Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
  Module: droidslam

test_exp_rgbd_orbslam2:
  Config: test_config_rgbd.yaml
  NumRuns: 2
  Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
  Module: orbslam2

# test_exp_rgbd_monogs:
#   Config: test_config_rgbd.yaml
#   NumRuns: 2
#   Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
#   Module: monogs

# test_exp_rgbd_pycuvslam:
#   Config: test_config_rgbd.yaml
#   NumRuns: 2
#   Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
#   Module: pycuvslam

test_exp_rgbd_orbslam3:
  Config: test_config_rgbd.yaml
  NumRuns: 2
  Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
  Module: orbslam3

test_exp_rgbd_droidslam_dev:
  Config: test_config_rgbd.yaml
  NumRuns: 2
  Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
  Module: droidslam-dev

test_exp_rgbd_orbslam2_dev:
  Config: test_config_rgbd.yaml
  NumRuns: 2
  Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
  Module: orbslam2-dev

# test_exp_rgbd_monogs_dev:
#   Config: test_config_rgbd.yaml
#   NumRuns: 2
#   Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
#   Module: monogs-dev

test_exp_rgbd_orbslam3_dev:
  Config: test_config_rgbd.yaml
  NumRuns: 2
  Parameters: {verbose: 0, rgb_idx: [0,999], mode: 'rgbd'}
  Module: orbslam3-dev